// Services (wrappers around ABP-generated proxies with firstValueFrom)
export {
  CourseCatalogService,
  CourseFieldService,
  CourseProposalService,
  TenantCourseService,
} from './services/training-proxy.service';
export { TrainingLocalizationHelper } from './services/training-localization.helper';

// Helpers
export { createAbpStore } from './helpers/create-abp-store';

// Shared components
export { NotesDrawerComponent } from './components/notes-drawer/notes-drawer.component';
export { ReturnModalComponent } from './components/return-modal/return-modal.component';
export { NominationPickerComponent } from './components/nomination-picker/nomination-picker.component';

// Local models (enums + localization maps — not generated by ABP proxy)
export * from './models/training-enums';

// Re-export ABP-generated DTO types for convenience
export type {
  CourseCatalogDto,
  CreateUpdateCourseCatalogDto,
  CourseCatalogGetListInput,
  CatalogEnrollmentConditionDto,
  CreateUpdateCatalogEnrollmentConditionDto,
} from '../../proxy/training/catalog/dtos';
export type {
  CourseFieldDto,
  CreateUpdateCourseFieldDto,
} from '../../proxy/training/course-fields/dtos';
export type {
  CourseProposalDto,
  CreateCourseProposalDto,
  ReviewCourseProposalDto,
  CourseProposalGetListInput,
} from '../../proxy/training/course-proposals/dtos';
export type {
  TenantCourseDto,
  AddFromCatalogDto,
  UpdateTenantCourseDto,
  TenantCourseGetListInput,
  TenantCourseConditionDto,
} from '../../proxy/training/tenant-courses/dtos';
export type {
  CasualCourseDto,
  CasualCourseDetailDto,
  CreateUpdateCasualCourseDto,
  CasualCourseGetListInput,
  AssignScenarioDto,
  StaffAdjustmentDto,
  FinancialOverrideDto,
  UpdateRankRateDto,
  CasualCourseFinancialDto,
  CasualCourseFinancialItemRankDto,
  CreateCasualCourseFinancialDto,
  CasualCourseNominationDto,
  RejectDto,
} from '../../proxy/training/casual-courses/dtos';
