using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace MOD.Training.Oranges;

public class OrangeManager : OrangeManagerBase
{
    //<suite-custom-code-autogenerated>
    public OrangeManager(IOrangeRepository orangeRepository) : base(orangeRepository)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}