using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp;

namespace MOD.Training.Oranges;

public class Orange : OrangeBase
{
    //<suite-custom-code-autogenerated>
    protected Orange()
    {
    }

    public Orange(Guid id, string arabicName) : base(id, arabicName)
    {
    }
    //</suite-custom-code-autogenerated>
    //Write your custom code...
}