using MOD.Training.Training.Enums;
using System;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;

namespace MOD.Training.Training.Payments;

/// <summary>
/// Audit-trail row recording that part of a casual course's funding-source budget was
/// reallocated to a destination FinancialItem when the course payment confirmed.
/// Auto-generated by <see cref="MOD.Training.Training.Managers.BudgetReallocationGenerator"/>;
/// the only client-side mutation is <c>MarkApproved</c>. Casual-course-only by design —
/// annual-plan sessions use single-budget funding and do not generate reallocations.
///
/// FundingSourceVoteCode is COPIED at generation time (not joined) so historical reallocations
/// remain stable even if the parent CasualCourse's funding source value changes later.
/// </summary>
public class BudgetReallocation : FullAuditedAggregateRoot<Guid>, IMultiTenant
{
    public Guid? TenantId { get; set; }

    public Guid CasualCourseId { get; set; }            // FK — required (casual courses only in 4B-β)
    public Guid CoursePaymentId { get; set; }           // FK — the payment whose Confirm triggered this row

    public string FundingSourceVoteCode { get; set; } = string.Empty;  // copied at generation; audit-stable
    public Guid ToFinancialItemId { get; set; }         // FK — destination financial item
    public decimal AmountOMR { get; set; }              // sum of all rank subtotals for this item

    public ReallocationStatus Status { get; set; }
    public DateTime? ApprovedAt { get; set; }
    public Guid? ApprovedById { get; set; }
    public string? ApprovalNote { get; set; }

    protected BudgetReallocation() { }

    public BudgetReallocation(Guid id) : base(id)
    {
        Status = ReallocationStatus.Pending;
    }
}
