using MOD.Training.Training.Payments.Dtos;
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace MOD.Training.Training.Payments;

/// <summary>
/// Read-only + status-transition only. Reallocations are auto-generated by
/// <c>CoursePaymentAppService.ConfirmAsync</c>; manual creation is forbidden.
/// </summary>
public interface IBudgetReallocationAppService : IApplicationService
{
    Task<BudgetReallocationDto> GetAsync(Guid id);
    Task<PagedResultDto<BudgetReallocationDto>> GetListAsync(BudgetReallocationGetListInput input);

    /// <summary>
    /// Staff records that the TD has signed off externally. Only valid when Status == Pending.
    /// </summary>
    Task<BudgetReallocationDto> MarkApprovedAsync(Guid id, MarkReallocationApprovedDto input);
}
